"""empty message

Revision ID: 9b9a351eade2
Revises: 
Create Date: 2023-03-03 20:26:26.063698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b9a351eade2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('productionPerHour', sa.String(), nullable=False))
    op.drop_column('products', 'quantityPerHour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantityPerHour', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('products', 'productionPerHour')
    # ### end Alembic commands ###
